---
title: "Week 5: Data Viz Principles"
output:
  revealjs::revealjs_presentation:
    theme: white
    center: true
    transition: none
    incremental: true
---


```{r setup, include=FALSE}
library(knitr)
library(formatR)
library(XML)
library(dplyr)
library(ggplot2)
knitr::opts_chunk$set(echo = TRUE)
```

## Exercise: Telling Stories with Data

- What does statistics mean to you?
- How about data science?
- data visualization?

## Exercise: Hans Rosling Discussion

- What did you learn from this movie?
- How did Hans Rosling use data visualization to tell a story?
- What principles from the visualization would you like to be able to do?



## Exercise: Why use Graphics

- Why do you, or have you, in the past used data graphics?
- What types of graphs have you used (feel free to sketch them)?


## Exercise: Visualizing Patterns Over Time

- What are we looking for with data over time?

## Exercise: Patterns over Time

Consider the number of bike rentals per hour per season

- Is this an example of continuous or discrete time?
- Make a figure to display your findings

## Exercise: Visualizing Proportions

- What to look for in proportions?

## Exercise: Visualizing Relationships

- When considering relationships between variables, what are we looking for?

## Exercise: Visualizing Relationships

- Summarize (visually) some relationship from the bike data set